import { Country } from "../types/Country";

export const COUNTRIES: Record<string, Country> = {
  AF: {
    name_pl: "Afganistan",
    name_en: "Afghanistan",
    iso2: "AF",
    iso3: "AFG",
  },
  AL: { name_pl: "Albania", name_en: "Albania", iso2: "AL", iso3: "ALB" },
  DZ: { name_pl: "Algieria", name_en: "Algeria", iso2: "DZ", iso3: "DZA" },
  AD: { name_pl: "Andora", name_en: "Andorra", iso2: "AD", iso3: "AND" },
  AO: { name_pl: "Angola", name_en: "Angola", iso2: "AO", iso3: "AGO" },
  AG: {
    name_pl: "Antigua i Barbuda",
    name_en: "Antigua and Barbuda",
    iso2: "AG",
    iso3: "ATG",
  },
  SA: {
    name_pl: "Arabia Saudyjska",
    name_en: "Saudi Arabia",
    iso2: "SA",
    iso3: "SAU",
  },
  AR: {
    name_pl: "Argentyna",
    name_en: "Argentina",
    iso2: "AR",
    iso3: "ARG",
  },
  AM: { name_pl: "Armenia", name_en: "Armenia", iso2: "AM", iso3: "ARM" },
  AU: {
    name_pl: "Australia",
    name_en: "Australia",
    iso2: "AU",
    iso3: "AUS",
  },
  AT: { name_pl: "Austria", name_en: "Austria", iso2: "AT", iso3: "AUT" },
  AZ: {
    name_pl: "Azerbejdżan",
    name_en: "Azerbaijan",
    iso2: "AZ",
    iso3: "AZE",
  },
  BS: { name_pl: "Bahamy", name_en: "Bahamas", iso2: "BS", iso3: "BHS" },
  BH: { name_pl: "Bahrajn", name_en: "Bahrain", iso2: "BH", iso3: "BHR" },
  BD: {
    name_pl: "Bangladesz",
    name_en: "Bangladesh",
    iso2: "BD",
    iso3: "BGD",
  },
  BB: { name_pl: "Barbados", name_en: "Barbados", iso2: "BB", iso3: "BRB" },
  BE: { name_pl: "Belgia", name_en: "Belgium", iso2: "BE", iso3: "BEL" },
  BZ: { name_pl: "Belize", name_en: "Belize", iso2: "BZ", iso3: "BLZ" },
  BJ: { name_pl: "Benin", name_en: "Benin", iso2: "BJ", iso3: "BEN" },
  BT: { name_pl: "Bhutan", name_en: "Bhutan", iso2: "BT", iso3: "BTN" },
  BY: { name_pl: "Białoruś", name_en: "Belarus", iso2: "BY", iso3: "BLR" },
  BO: {
    name_pl: "Boliwia",
    name_en: "Bolivia, Plurinational State of",
    iso2: "BO",
    iso3: "BOL",
  },
  BA: {
    name_pl: "Bośnia i Hercegowina",
    name_en: "Bosnia and Herzegovina",
    iso2: "BA",
    iso3: "BIH",
  },
  BW: { name_pl: "Botswana", name_en: "Botswana", iso2: "BW", iso3: "BWA" },
  BR: { name_pl: "Brazylia", name_en: "Brazil", iso2: "BR", iso3: "BRA" },
  BN: {
    name_pl: "Brunei",
    name_en: "Brunei Darussalam",
    iso2: "BN",
    iso3: "BRN",
  },
  BG: { name_pl: "Bułgaria", name_en: "Bulgaria", iso2: "BG", iso3: "BGR" },
  BF: {
    name_pl: "Burkina Faso",
    name_en: "Burkina Faso",
    iso2: "BF",
    iso3: "BFA",
  },
  BI: { name_pl: "Burundi", name_en: "Burundi", iso2: "BI", iso3: "BDI" },
  CL: { name_pl: "Chile", name_en: "Chile", iso2: "CL", iso3: "CHL" },
  CN: { name_pl: "Chiny", name_en: "China", iso2: "CN", iso3: "CHN" },
  HR: { name_pl: "Chorwacja", name_en: "Croatia", iso2: "HR", iso3: "HRV" },
  CY: { name_pl: "Cypr", name_en: "Cyprus", iso2: "CY", iso3: "CYP" },
  TD: { name_pl: "Czad", name_en: "Chad", iso2: "TD", iso3: "TCD" },
  ME: {
    name_pl: "Czarnogóra",
    name_en: "Montenegro",
    iso2: "ME",
    iso3: "MNE",
  },
  CZ: {
    name_pl: "Czechy",
    name_en: "Czech Republic",
    iso2: "CZ",
    iso3: "CZE",
  },
  DK: { name_pl: "Dania", name_en: "Denmark", iso2: "DK", iso3: "DNK" },

  DM: { name_pl: "Dominika", name_en: "Dominica", iso2: "DM", iso3: "DMA" },
  DO: {
    name_pl: "Dominikana",
    name_en: "Dominican Republic",
    iso2: "DO",
    iso3: "DOM",
  },
  DJ: { name_pl: "Dżibuti", name_en: "Djibouti", iso2: "DJ", iso3: "DJI" },
  EG: { name_pl: "Egipt", name_en: "Egypt", iso2: "EG", iso3: "EGY" },
  EC: { name_pl: "Ekwador", name_en: "Ecuador", iso2: "EC", iso3: "ECU" },
  ER: { name_pl: "Erytrea", name_en: "Eritrea", iso2: "ER", iso3: "ERI" },
  EE: { name_pl: "Estonia", name_en: "Estonia", iso2: "EE", iso3: "EST" },
  ET: { name_pl: "Etiopia", name_en: "Ethiopia", iso2: "ET", iso3: "ETH" },

  FJ: { name_pl: "Fidżi", name_en: "Fiji", iso2: "FJ", iso3: "FJI" },
  PH: {
    name_pl: "Filipiny",
    name_en: "Philippines",
    iso2: "PH",
    iso3: "PHL",
  },
  FI: { name_pl: "Finlandia", name_en: "Finland", iso2: "FI", iso3: "FIN" },
  FR: { name_pl: "Francja", name_en: "France", iso2: "FR", iso3: "FRA" },

  GA: { name_pl: "Gabon", name_en: "Gabon", iso2: "GA", iso3: "GAB" },
  GM: { name_pl: "Gambia", name_en: "Gambia", iso2: "GM", iso3: "GMB" },

  GH: { name_pl: "Ghana", name_en: "Ghana", iso2: "GH", iso3: "GHA" },
  GR: { name_pl: "Grecja", name_en: "Greece", iso2: "GR", iso3: "GRC" },
  GD: { name_pl: "Grenada", name_en: "Grenada", iso2: "GD", iso3: "GRD" },
  GE: { name_pl: "Gruzja", name_en: "Georgia", iso2: "GE", iso3: "GEO" },
  GY: { name_pl: "Gujana", name_en: "Guyana", iso2: "GY", iso3: "GUY" },
  GT: {
    name_pl: "Gwatemala",
    name_en: "Guatemala",
    iso2: "GT",
    iso3: "GTM",
  },
  GW: {
    name_pl: "Gwinea Bissau",
    name_en: "Guinea-Bissau",
    iso2: "GW",
    iso3: "GNB",
  },
  GQ: {
    name_pl: "Gwinea Równikowa",
    name_en: "Equatorial Guinea",
    iso2: "GQ",
    iso3: "GNQ",
  },
  GN: { name_pl: "Gwinea", name_en: "Guinea", iso2: "GN", iso3: "GIN" },
  HT: { name_pl: "Haiti", name_en: "Haiti", iso2: "HT", iso3: "HTI" },
  ES: { name_pl: "Hiszpania", name_en: "Spain", iso2: "ES", iso3: "ESP" },
  NL: {
    name_pl: "Holandia",
    name_en: "Netherlands",
    iso2: "NL",
    iso3: "NLD",
  },
  HN: { name_pl: "Honduras", name_en: "Honduras", iso2: "HN", iso3: "HND" },
  IN: { name_pl: "Indie", name_en: "India", iso2: "IN", iso3: "IND" },
  ID: {
    name_pl: "Indonezja",
    name_en: "Indonesia",
    iso2: "ID",
    iso3: "IDN",
  },
  IQ: { name_pl: "Irak", name_en: "Iraq", iso2: "IQ", iso3: "IRQ" },
  IR: {
    name_pl: "Iran",
    name_en: "Iran, Islamic Republic of",
    iso2: "IR",
    iso3: "IRN",
  },
  IE: { name_pl: "Irlandia", name_en: "Ireland", iso2: "IE", iso3: "IRL" },
  IS: { name_pl: "Islandia", name_en: "Iceland", iso2: "IS", iso3: "ISL" },
  IL: { name_pl: "Izrael", name_en: "Israel", iso2: "IL", iso3: "ISR" },
  JM: { name_pl: "Jamajka", name_en: "Jamaica", iso2: "JM", iso3: "JAM" },
  JP: { name_pl: "Japonia", name_en: "Japan", iso2: "JP", iso3: "JPN" },
  YE: { name_pl: "Jemen", name_en: "Yemen", iso2: "YE", iso3: "YEM" },
  JO: { name_pl: "Jordania", name_en: "Jordan", iso2: "JO", iso3: "JOR" },
  KH: { name_pl: "Kambodża", name_en: "Cambodia", iso2: "KH", iso3: "KHM" },
  CM: { name_pl: "Kamerun", name_en: "Cameroon", iso2: "CM", iso3: "CMR" },
  CA: { name_pl: "Kanada", name_en: "Canada", iso2: "CA", iso3: "CAN" },
  QA: { name_pl: "Katar", name_en: "Qatar", iso2: "QA", iso3: "QAT" },
  KZ: {
    name_pl: "Kazachstan",
    name_en: "Kazakhstan",
    iso2: "KZ",
    iso3: "KAZ",
  },
  KE: { name_pl: "Kenia", name_en: "Kenya", iso2: "KE", iso3: "KEN" },
  KG: {
    name_pl: "Kirgistan",
    name_en: "Kyrgyzstan",
    iso2: "KG",
    iso3: "KGZ",
  },
  CO: { name_pl: "Kolumbia", name_en: "Colombia", iso2: "CO", iso3: "COL" },
  KM: { name_pl: "Komory", name_en: "Comoros", iso2: "KM", iso3: "COM" },
  KR: {
    name_pl: "Korea Południowa",
    name_en: "Korea, Republic of",
    iso2: "KR",
    iso3: "KOR",
  },
  CR: {
    name_pl: "Kostaryka",
    name_en: "Costa Rica",
    iso2: "CR",
    iso3: "CRI",
  },
  CU: { name_pl: "Kuba", name_en: "Cuba", iso2: "CU", iso3: "CUB" },
  KW: { name_pl: "Kuwejt", name_en: "Kuwait", iso2: "KW", iso3: "KWT" },
  LA: {
    name_pl: "Laos",
    name_en: "Lao People's Democratic Republic",
    iso2: "LA",
    iso3: "LAO",
  },
  LS: { name_pl: "Lesotho", name_en: "Lesotho", iso2: "LS", iso3: "LSO" },
  LB: { name_pl: "Liban", name_en: "Lebanon", iso2: "LB", iso3: "LBN" },
  LR: { name_pl: "Liberia", name_en: "Liberia", iso2: "LR", iso3: "LBR" },
  LY: {
    name_pl: "Libia",
    name_en: "Libyan Arab Jamahiriya",
    iso2: "LY",
    iso3: "LBY",
  },
  LI: {
    name_pl: "Liechtenstein",
    name_en: "Liechtenstein",
    iso2: "LI",
    iso3: "LIE",
  },
  LT: { name_pl: "Litwa", name_en: "Lithuania", iso2: "LT", iso3: "LTU" },
  LU: {
    name_pl: "Luksemburg",
    name_en: "Luxembourg",
    iso2: "LU",
    iso3: "LUX",
  },
  LV: { name_pl: "Łotwa", name_en: "Latvia", iso2: "LV", iso3: "LVA" },
  MG: {
    name_pl: "Madagaskar",
    name_en: "Madagascar",
    iso2: "MG",
    iso3: "MDG",
  },
  MW: { name_pl: "Malawi", name_en: "Malawi", iso2: "MW", iso3: "MWI" },
  MV: { name_pl: "Malediwy", name_en: "Maldives", iso2: "MV", iso3: "MDV" },
  MY: { name_pl: "Malezja", name_en: "Malaysia", iso2: "MY", iso3: "MYS" },
  ML: { name_pl: "Mali", name_en: "Mali", iso2: "ML", iso3: "MLI" },
  MT: { name_pl: "Malta", name_en: "Malta", iso2: "MT", iso3: "MLT" },
  MA: { name_pl: "Maroko", name_en: "Morocco", iso2: "MA", iso3: "MAR" },
  MR: {
    name_pl: "Mauretania",
    name_en: "Mauritania",
    iso2: "MR",
    iso3: "MRT",
  },
  MU: {
    name_pl: "Mauritius",
    name_en: "Mauritius",
    iso2: "MU",
    iso3: "MUS",
  },
  MX: { name_pl: "Meksyk", name_en: "Mexico", iso2: "MX", iso3: "MEX" },
  MD: {
    name_pl: "Mołdawia",
    name_en: "Moldova, Republic of",
    iso2: "MD",
    iso3: "MDA",
  },
  MC: { name_pl: "Monako", name_en: "Monaco", iso2: "MC", iso3: "MCO" },
  MN: { name_pl: "Mongolia", name_en: "Mongolia", iso2: "MN", iso3: "MNG" },
  MZ: {
    name_pl: "Mozambik",
    name_en: "Mozambique",
    iso2: "MZ",
    iso3: "MOZ",
  },
  NA: { name_pl: "Namibia", name_en: "Namibia", iso2: "NA", iso3: "NAM" },
  NP: { name_pl: "Nepal", name_en: "Nepal", iso2: "NP", iso3: "NPL" },
  DE: { name_pl: "Niemcy", name_en: "Germany", iso2: "DE", iso3: "DEU" },
  NE: { name_pl: "Niger", name_en: "Niger", iso2: "NE", iso3: "NER" },
  NG: { name_pl: "Nigeria", name_en: "Nigeria", iso2: "NG", iso3: "NGA" },
  NI: {
    name_pl: "Nikaragua",
    name_en: "Nicaragua",
    iso2: "NI",
    iso3: "NIC",
  },
  NO: { name_pl: "Norwegia", name_en: "Norway", iso2: "NO", iso3: "NOR" },
  NZ: {
    name_pl: "Nowa Zelandia",
    name_en: "New Zealand",
    iso2: "NZ",
    iso3: "NZL",
  },
  OM: { name_pl: "Oman", name_en: "Oman", iso2: "OM", iso3: "OMN" },
  PK: { name_pl: "Pakistan", name_en: "Pakistan", iso2: "PK", iso3: "PAK" },
  PA: { name_pl: "Panama", name_en: "Panama", iso2: "PA", iso3: "PAN" },
  PG: {
    name_pl: "Papua-Nowa Gwinea",
    name_en: "Papua New Guinea",
    iso2: "PG",
    iso3: "PNG",
  },
  PY: { name_pl: "Paragwaj", name_en: "Paraguay", iso2: "PY", iso3: "PRY" },
  PE: { name_pl: "Peru", name_en: "Peru", iso2: "PE", iso3: "PER" },
  PL: { name_pl: "Polska", name_en: "Poland", iso2: "PL", iso3: "POL" },
  PT: {
    name_pl: "Portugalia",
    name_en: "Portugal",
    iso2: "PT",
    iso3: "PRT",
  },
  ZA: {
    name_pl: "Republika Południowej Afryki",
    name_en: "South Africa",
    iso2: "ZA",
    iso3: "ZAF",
  },
  CF: {
    name_pl: "Republika Środkowoafrykańska",
    name_en: "Central African Republic",
    iso2: "CF",
    iso3: "CAF",
  },
  RU: {
    name_pl: "Rosja",
    name_en: "Russian Federation",
    iso2: "RU",
    iso3: "RUS",
  },
  RO: { name_pl: "Rumunia", name_en: "Romania", iso2: "RO", iso3: "ROU" },
  RW: { name_pl: "Rwanda", name_en: "Rwanda", iso2: "RW", iso3: "RWA" },
  EH: {
    name_pl: "Sahara Zachodnia",
    name_en: "Western Sahara",
    iso2: "EH",
    iso3: "ESH",
  },
  KN: {
    name_pl: "Saint Kitts i Nevis",
    name_en: "Saint Kitts and Nevis",
    iso2: "KN",
    iso3: "KNA",
  },
  LC: {
    name_pl: "Saint Lucia",
    name_en: "Saint Lucia",
    iso2: "LC",
    iso3: "LCA",
  },
  VC: {
    name_pl: "Saint Vincent i Grenadyny",
    name_en: "Saint Vincent and the Grenadines",
    iso2: "VC",
    iso3: "VCT",
  },
  SV: {
    name_pl: "Salwador",
    name_en: "El Salvador",
    iso2: "SV",
    iso3: "SLV",
  },
  SM: {
    name_pl: "San Marino",
    name_en: "San Marino",
    iso2: "SM",
    iso3: "SMR",
  },
  SN: { name_pl: "Senegal", name_en: "Senegal", iso2: "SN", iso3: "SEN" },
  RS: { name_pl: "Serbia", name_en: "Serbia", iso2: "RS", iso3: "SRB" },
  SC: {
    name_pl: "Seszele",
    name_en: "Seychelles",
    iso2: "SC",
    iso3: "SYC",
  },
  SL: {
    name_pl: "Sierra Leone",
    name_en: "Sierra Leone",
    iso2: "SL",
    iso3: "SLE",
  },
  SG: {
    name_pl: "Singapur",
    name_en: "Singapore",
    iso2: "SG",
    iso3: "SGP",
  },
  SK: { name_pl: "Słowacja", name_en: "Slovakia", iso2: "SK", iso3: "SVK" },
  SI: { name_pl: "Słowenia", name_en: "Slovenia", iso2: "SI", iso3: "SVN" },
  SO: { name_pl: "Somalia", name_en: "Somalia", iso2: "SO", iso3: "SOM" },
  LK: {
    name_pl: "Sri Lanka",
    name_en: "Sri Lanka",
    iso2: "LK",
    iso3: "LKA",
  },
  US: {
    name_pl: "Stany Zjednoczone",
    name_en: "United States",
    iso2: "US",
    iso3: "USA",
  },
  SD: { name_pl: "Sudan", name_en: "Sudan", iso2: "SD", iso3: "SDN" },
  SS: {
    name_pl: "Sudan Południowy",
    name_en: "South Sudan",
    iso2: "SS",
    iso3: "SSD",
  },
  SR: { name_pl: "Surinam", name_en: "Suriname", iso2: "SR", iso3: "SUR" },
  SY: {
    name_pl: "Syria",
    name_en: "Syrian Arab Republic",
    iso2: "SY",
    iso3: "SYR",
  },
  CH: {
    name_pl: "Szwajcaria",
    name_en: "Switzerland",
    iso2: "CH",
    iso3: "CHE",
  },
  SE: { name_pl: "Szwecja", name_en: "Sweden", iso2: "SE", iso3: "SWE" },
  TJ: {
    name_pl: "Tadżykistan",
    name_en: "Tajikistan",
    iso2: "TJ",
    iso3: "TJK",
  },
  TH: {
    name_pl: "Tajlandia",
    name_en: "Thailand",
    iso2: "TH",
    iso3: "THA",
  },
  TW: {
    name_pl: "Tajwan",
    name_en: "Taiwan, Province of China",
    iso2: "TW",
    iso3: "TWN",
  },
  TZ: {
    name_pl: "Tanzania",
    name_en: "Tanzania, United Republic of",
    iso2: "TZ",
    iso3: "TZA",
  },
  TG: { name_pl: "Togo", name_en: "Togo", iso2: "TG", iso3: "TGO" },
  TT: {
    name_pl: "Trynidad i Tobago",
    name_en: "Trinidad and Tobago",
    iso2: "TT",
    iso3: "TTO",
  },
  TN: { name_pl: "Tunezja", name_en: "Tunisia", iso2: "TN", iso3: "TUN" },
  TR: { name_pl: "Turcja", name_en: "Turkey", iso2: "TR", iso3: "TUR" },
  UG: { name_pl: "Uganda", name_en: "Uganda", iso2: "UG", iso3: "UGA" },
  UA: { name_pl: "Ukraina", name_en: "Ukraine", iso2: "UA", iso3: "UKR" },
  UY: { name_pl: "Urugwaj", name_en: "Uruguay", iso2: "UY", iso3: "URY" },
  UZ: {
    name_pl: "Uzbekistan",
    name_en: "Uzbekistan",
    iso2: "UZ",
    iso3: "UZB",
  },
  VU: { name_pl: "Vanuatu", name_en: "Vanuatu", iso2: "VU", iso3: "VUT" },
  VE: {
    name_pl: "Wenezuela",
    name_en: "Venezuela, Bolivarian Republic of",
    iso2: "VE",
    iso3: "VEN",
  },
  HU: { name_pl: "Węgry", name_en: "Hungary", iso2: "HU", iso3: "HUN" },
  GB: {
    name_pl: "Wielka Brytania",
    name_en: "United Kingdom",
    iso2: "GB",
    iso3: "GBR",
  },
  VN: { name_pl: "Wietnam", name_en: "Viet Nam", iso2: "VN", iso3: "VNM" },
  IT: { name_pl: "Włochy", name_en: "Italy", iso2: "IT", iso3: "ITA" },
  MH: {
    name_pl: "Wyspy Marshalla",
    name_en: "Marshall Islands",
    iso2: "MH",
    iso3: "MHL",
  },
  SB: {
    name_pl: "Wyspy Salomona",
    name_en: "Solomon Islands",
    iso2: "SB",
    iso3: "SLB",
  },
  ST: {
    name_pl: "Wyspy Świętego Tomasza i Książęca",
    name_en: "Sao Tome and Principe",
    iso2: "ST",
    iso3: "STP",
  },
  ZM: { name_pl: "Zambia", name_en: "Zambia", iso2: "ZM", iso3: "ZMB" },
  ZW: { name_pl: "Zimbabwe", name_en: "Zimbabwe", iso2: "ZW", iso3: "ZWE" },
  AE: {
    name_pl: "Zjednoczone Emiraty Arabskie",
    name_en: "United Arab Emirates",
    iso2: "AE",
    iso3: "ARE",
  },
};
